CREATE ROLE wb_lvl0
    LOGIN
    NOSUPERUSER
    INHERIT
    NOCREATEROLE
    NOCREATEDB
    NOREPLICATION
    NOBYPASSRLS
    PASSWORD 'SCRAM-SHA-256$4096:DmDC6PAP1kgc2DBSNrHkDA==$HwYaV2YB8u56u/RO44xIY9cYa7/Tdy0mrlncQtWbDZU=:5yBdfHggIWHqeogKy1/bxdsBM1vadT+uRI/cXQEU/cc=';

GRANT CONNECT ON DATABASE wb_lvl0 TO wb_lvl0;

GRANT USAGE ON SCHEMA public TO wb_lvl0;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO wb_lvl0;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO wb_lvl0;
